### ISSUE TITLE
Add a pull policy for container images

### ISSUE THREAD

**Issue by askfor** [batect/batect#600] opened 2020-07-12 14:56 UTC
I think there should be a pull policy for container images, so a user can choose to always pull images even the image exists.

**Comment by charleskorn** [comment] 2020-07-12 22:55
Hey @askfor, thanks for the suggestion. Could you tell me a little bit more about your use case? 

(I'm hesitant to add something like this as it would have a significant impact on performance, but if there's a compelling use case for it, I'm open to changing my mind.)

**Comment by askfor** [comment] 2020-07-13 00:13
Some images use latest tag, when it was updated, it won't be updated if there is not a pull policy force it always pulls image.
It could be an option user can set, k8s has a similar setting.
https://kubernetes.io/docs/concepts/containers/images/#updating-images

**Comment by charleskorn** [comment] 2020-07-13 11:09
Could you give me an example of an image that requires you to use `latest`?

**Comment by askfor** [comment] 2020-07-13 15:54
> Could you give me an example of an image that requires you to use `latest`?

mostly self-made image, so we didn't want to give them a version for convenience.

**Comment by charleskorn** [comment] 2020-07-13 22:41
I'd very strongly encourage you to tag your images with versions and keep those tags immutable. Not only does it have the performance benefit of not needing to pull `latest` every time you run a task, but it also makes your tasks predictable and reproducible - one of the major goals of batect. 

>we didn't want to give them a version for convenience

Is this because updating image tags in a project (or across many projects) is difficult? One of the things I've been wanting to do for a while is add support for batect to Dependabot (or another similar tool like Renovate) to make this easy. Would something like that solve this problem for you?

**Comment by askfor** [comment] 2020-07-14 03:04
I agree that use a fixed version image is a good practice.
But sometimes use latest images is also desirable. For example, the container image itself is under development, so there are lots of updates going on.
Always pull the latest image isn't much a performance impact as it sounds. if the images hash not changed there won't be a real pull. And it's a policy user change set plus it can be default off anyway.

**Comment by charleskorn** [comment] 2020-07-15 07:45
Are these for Docker images you are modifying yourself? In that case, another option that might be even more convenient is to refer to the image's build directory directly with `build_directory` rather than needing to build and push the image somewhere.

**Comment by askfor** [comment] 2020-07-15 08:25
Yes, these images are maintained by ourselves( maybe different teams) . But build_directory won't always be feasible, those dockerfile could be in different repositories.

**Comment by charleskorn** [comment] 2020-07-20 08:38
Right, makes sense. I'll add this to my backlog, but can't make any promises when it will be available. I'm always open to PRs if you'd be interested in contributing :)

**Comment by charleskorn** [comment] 2020-08-04 04:52
I've just implemented this and it will be in the next release (0.58). Thanks again for the suggestion @askfor!

**Closed** 2020-08-04 04:52 UTC
Labels: good first issue, is:enhancement
