### ISSUE TITLE
batect.cmd broken on windows with powershell core installed

### ISSUE THREAD

**Issue by yoyo-ohno** [batect/batect#1350] opened 2022-09-15 22:38 UTC
### Describe the bug

Seems to be the same issue from #627 

Reinstating @thirkcircus' original fix from #629 fixes the issue for me.

### Steps to reproduce

In powershell core 
![image](https://user-images.githubusercontent.com/66757187/190520729-7c7b92ef-eb27-44fe-9eab-50f32e34ba0c.png)

Run `./batect -T`

### Expected behaviour

Available tasks are listed

### Actual behaviour

![image](https://user-images.githubusercontent.com/66757187/190518817-63eedf91-f45f-470d-9795-f26d0936ffc7.png)

### Version information

```plain text
Same behavior on `0.70.1` (version from screenshot), and `0.81.1`
```

**Comment by charleskorn** [comment] 2022-09-15 23:41
Thanks for the bug report @yoyo-ohno.

Just so I'm clear, would you be able to share a diff with the changes you've made to `batect.cmd`?

**Comment by charleskorn** [comment] 2022-09-19 00:38
Sorry, one last question: has this always been broken for you? Or has it only been broken as of a particular Batect version?

**Comment by yoyo-ohno** [comment] 2022-09-19 01:42
To be honest I'm not 100% sure - have switched back and forward between bash, windows powershell & pscore since first using batect so I'm quite hazy on when what worked where

**Comment by charleskorn** [comment] 2022-09-19 03:22
Hmmm... I'm not able to reproduce this issue. I've tried running Batect from both a vanilla PowerShell (`powershell`) and PowerShell Core (`pwsh`) prompt and it works fine in both cases without the change you've suggested.

I'm running the same version of PowerShell Core and Windows as you - are there any other details that might be relevant? 

Also, is `$PSModulePath` set on your machine? (It's empty for me.)

**Comment by yoyo-ohno** [comment] 2022-09-19 20:23
Oh. I had `$PSModulePath = C:\Program Files\PowerShell\7\Modules` set in user variables and removing it fixes the issue 🙌

**Comment by charleskorn** [comment] 2022-09-20 03:29
Awesome 🎉 Are you happy for me to close this issue?

**Comment by yoyo-ohno** [comment] 2022-09-23 04:07
Yep! Thanks for all your help 🙏

**Closed** 2022-09-23 04:09 UTC
Labels: is:bug
