### ISSUE TITLE
Version 0.83.8 fails on Apple M1 chip

### ISSUE THREAD

**Issue by balasurajgajula** [batect/batect#1542] opened 2023-06-08 12:24 UTC
### Describe the bug

**batect** `0.83.8` fails with the following error on Apple M1

I've just ran the `./batect --version` command & it gave me this
```
minpc= 0x12e1f8950 min= 0x12e1f8950 maxpc= 0x12e9c8180 max= 0x12e9c1070
 fatal error: minpc or maxpc invalid
 runtime: panic before malloc heap initialized
 
 runtime stack:
 runtime.throw({0x12e9da7dd?, 0x0?})
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/panic.go:1047 +0x40 fp=0x16e7b2e60 sp=0x16e7b2e30 pc=0x12e22fe20
 runtime.moduledataverify1(0x12f2d1ea0)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:636 +0x41c fp=0x16e7b2f40 sp=0x16e7b2e60 pc=0x12e24d22c
 runtime.moduledataverify(...)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:593
 runtime.schedinit()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/proc.go:691 +0x40 fp=0x16e7b2fa0 sp=0x16e7b2f40 pc=0x12e2334e0
 runtime.rt0_go()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/asm_arm64.s:86 +0xd0 fp=0x16e7b2fd0 sp=0x16e7b2fa0 pc=0x12e25e630
```

### Steps to reproduce

- Install batect `0.83.8` on Apple M1
- Run `./batect --version`

### Expected behaviour

- When we run `./batect --version`, it should give something like the following

```
Batect version:    0.83.7
 Built:             2023-05-19 01:27:00 +0000
 Built from commit: 18d7a7e53ec17051febde6b760d4ed32e17d7a09 (commit date: 2023-05-19 11:08:39 +1000)
 JVM version:       Amazon.com Inc. OpenJDK 64-Bit Server VM 20.0.1
 OS version:        Mac OS X 13.4 aarch64
 Docker version:    24.0.2 (API version: 1.43, minimum supported API version: 1.12, commit: 659604f, operating system: 'linux', architecture: 'arm64', experimental: false)
 Git version:       2.41.0
 
 For documentation and further information on Batect, visit https://github.com/batect/batect.
```

### Actual behaviour

- But, it is giving the following error

```
minpc= 0x12e1f8950 min= 0x12e1f8950 maxpc= 0x12e9c8180 max= 0x12e9c1070
 fatal error: minpc or maxpc invalid
 runtime: panic before malloc heap initialized
 
 runtime stack:
 runtime.throw({0x12e9da7dd?, 0x0?})
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/panic.go:1047 +0x40 fp=0x16e7b2e60 sp=0x16e7b2e30 pc=0x12e22fe20
 runtime.moduledataverify1(0x12f2d1ea0)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:636 +0x41c fp=0x16e7b2f40 sp=0x16e7b2e60 pc=0x12e24d22c
 runtime.moduledataverify(...)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:593
 runtime.schedinit()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/proc.go:691 +0x40 fp=0x16e7b2fa0 sp=0x16e7b2f40 pc=0x12e2334e0
 runtime.rt0_go()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/asm_arm64.s:86 +0xd0 fp=0x16e7b2fd0 sp=0x16e7b2fa0 pc=0x12e25e630
```

### Version information

```plain text
(Providing version information for 0.83.7 version)
Batect version:    0.83.7
 Built:             2023-05-19 01:27:00 +0000
 Built from commit: 18d7a7e53ec17051febde6b760d4ed32e17d7a09 (commit date: 2023-05-19 11:08:39 +1000)
 JVM version:       Amazon.com Inc. OpenJDK 64-Bit Server VM 20.0.1
 OS version:        Mac OS X 13.4 aarch64
 Docker version:    24.0.2 (API version: 1.43, minimum supported API version: 1.12, commit: 659604f, operating system: 'linux', architecture: 'arm64', experimental: false)
 Git version:       2.41.0
 
 For documentation and further information on Batect, visit https://github.com/batect/batect.
```

### Any other information

This issue seems to be similar to #1474

**Comment by charleskorn** [comment] 2023-06-12 01:18
Thanks for the bug report @balasurajgajula. While I'm investigating, please use an earlier version that works (eg. 0.83.7).

**Comment by balasurajgajula** [comment] 2023-06-12 04:54
Sure, @charleskorn 

I would also like to provide an additional information regarding the compatibility
### When I use batect `0.83.7`
- In Amazon Linux 2, it gives following error
```
Fatal exception: 
 java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
 
 Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type POINTER, original error message follows: java.lang.UnsatisfiedLinkError: Unable to execute or load jffi binary stub from /tmp. Set TMPDIR or Java property java.io.tmpdir to a read/write path that is not mounted "noexec".
 /lib64/libc.so.6: version `GLIBC_2.27' not found
```

- In Apple M1, it works! ✅ 

### Again, when I use batect `0.83.8`
- In Amazon Linux 2, it works! ✅ 
- In Apple M1, it gives the following error
```
minpc= 0x12e1f8950 min= 0x12e1f8950 maxpc= 0x12e9c8180 max= 0x12e9c1070
 fatal error: minpc or maxpc invalid
 runtime: panic before malloc heap initialized
 
 runtime stack:
 runtime.throw({0x12e9da7dd?, 0x0?})
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/panic.go:1047 +0x40 fp=0x16e7b2e60 sp=0x16e7b2e30 pc=0x12e22fe20
 runtime.moduledataverify1(0x12f2d1ea0)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:636 +0x41c fp=0x16e7b2f40 sp=0x16e7b2e60 pc=0x12e24d22c
 runtime.moduledataverify(...)
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/symtab.go:593
 runtime.schedinit()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/proc.go:691 +0x40 fp=0x16e7b2fa0 sp=0x16e7b2f40 pc=0x12e2334e0
 runtime.rt0_go()
     /Users/runner/work/docker-client/docker-client/golang-wrapper/build/tools/golang-1.19.9/src/runtime/asm_arm64.s:86 +0xd0 fp=0x16e7b2fd0 sp=0x16e7b2fa0 pc=0x12e25e630
```

**Comment by charleskorn** [comment] 2023-06-17 07:33
Sorry again for this. This should be fixed with [0.83.9](https://github.com/batect/batect/releases/tag/0.83.9).

**Closed by charleskorn** 2023-06-17 07:33 UTC
Labels: is:bug

**Comment by pexa-srisudarsan** [comment] 2023-06-28 04:42
Thanks @charleskorn , can I please know the cause / fix for my knowledge please ?

**Comment by srisudarsan** [comment] 2023-06-28 04:51
Thanks a lot @charleskorn , Can I please know the cause / fix for this issue for my knowledge ?
had a look at the diff which had a couple of dependency upgrades, but not sure what the fix was

**Comment by charleskorn** [comment] 2023-07-03 01:30
The issue was a bug in either the Golang compiler or the Zig compiler (or an interaction between the two). Rebuilding docker-client resolved the issue.
